// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {domain} from '../models';

export function AutoRunEnabled(arg1:string):Promise<boolean>;

export function CreateProject(arg1:app.CreateProjectRequest):Promise<domain.Project>;

export function CreateTask(arg1:app.CreateTaskRequest):Promise<domain.Task>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function DispatchOnce(arg1:string,arg2:string):Promise<app.DispatchResponse>;

export function FinishRun(arg1:app.FinishRunRequest):Promise<void>;

export function GetGlobalSettings():Promise<app.GlobalSettingsView>;

export function GetTaskDetail(arg1:string):Promise<app.TaskDetailView>;

export function GetTaskLatestRun(arg1:string):Promise<app.TaskLatestRunView>;

export function Greet(arg1:string):Promise<string>;

export function Health():Promise<string>;

export function ListAgents():Promise<Array<domain.Agent>>;

export function ListProjects(arg1:number):Promise<Array<domain.Project>>;

export function ListRunLogs(arg1:string,arg2:number):Promise<Array<app.RunLogEventView>>;

export function ListRunningRuns(arg1:string,arg2:number):Promise<Array<app.RunningRunView>>;

export function ListSystemLogs(arg1:string,arg2:number):Promise<Array<app.SystemLogView>>;

export function ListTasks(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<domain.Task>>;

export function MCPStatus():Promise<app.MCPStatusView>;

export function RetryTask(arg1:string):Promise<void>;

export function SetAutoRunEnabled(arg1:string,arg2:boolean):Promise<boolean>;

export function UpdateGlobalSettings(arg1:app.UpdateGlobalSettingsRequest):Promise<app.GlobalSettingsView>;

export function UpdateProject(arg1:app.UpdateProjectRequest):Promise<domain.Project>;

export function UpdateProjectAIConfig(arg1:app.UpdateProjectAIConfigRequest):Promise<domain.Project>;

export function UpdateTask(arg1:app.UpdateTaskRequest):Promise<domain.Task>;

export function UpdateTaskStatus(arg1:string,arg2:string):Promise<void>;
