// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoRunEnabled(arg1) {
  return window['go']['main']['App']['AutoRunEnabled'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DispatchOnce(arg1, arg2) {
  return window['go']['main']['App']['DispatchOnce'](arg1, arg2);
}

export function FinishRun(arg1) {
  return window['go']['main']['App']['FinishRun'](arg1);
}

export function GetGlobalSettings() {
  return window['go']['main']['App']['GetGlobalSettings']();
}

export function GetTaskDetail(arg1) {
  return window['go']['main']['App']['GetTaskDetail'](arg1);
}

export function GetTaskLatestRun(arg1) {
  return window['go']['main']['App']['GetTaskLatestRun'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ListRunLogs(arg1, arg2) {
  return window['go']['main']['App']['ListRunLogs'](arg1, arg2);
}

export function ListRunningRuns(arg1, arg2) {
  return window['go']['main']['App']['ListRunningRuns'](arg1, arg2);
}

export function ListSystemLogs(arg1, arg2) {
  return window['go']['main']['App']['ListSystemLogs'](arg1, arg2);
}

export function ListTasks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListTasks'](arg1, arg2, arg3, arg4);
}

export function MCPStatus(arg1) {
  return window['go']['main']['App']['MCPStatus'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function SetAutoRunEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAutoRunEnabled'](arg1, arg2);
}

export function UpdateGlobalSettings(arg1) {
  return window['go']['main']['App']['UpdateGlobalSettings'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateProjectAIConfig(arg1) {
  return window['go']['main']['App']['UpdateProjectAIConfig'](arg1);
}

export function UpdateTask(arg1) {
  return window['go']['main']['App']['UpdateTask'](arg1);
}

export function UpdateTaskStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1, arg2);
}
